
name: Unzip ZIP Automatically

on:
  push:
    paths:
      - '**.zip'
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Find and unzip ZIP files
        run: |
          mkdir -p unzipped
          for file in *.zip; do
            unzip -o "$file" -d "unzipped/${file%.*}"
          done

      - name: Commit unzipped content
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add unzipped/
          git commit -m "Auto unzip uploaded ZIP file"
          git push
